### ISSUE TITLE
camera.py运行自动闪退了

### ISSUE THREAD

**Issue by DWCTOD** [github-luffy/PFLD_68points_Pytorch#1]
运行 camera.py 自动会闪退
AttributeError: 'BlazeLandMark' object has no attribute 'secondconv'
无论是用 视频文件还是接摄像头都会闪退
这里我的权重文件是用项目中提供的 model_10.pth

**Comment by github-luffy** [comment]
不好意思 这个模型是不能用的 我重新上传一个模型文件 你试试看

**Comment by github-luffy** [comment]
上传的模型暂时只是用了300W与WFLW训练出来的，68点特征点 你试试看 [best_model.pth](https://github.com/github-luffy/PFLD_68points_Pytorch/tree/master/pretrained_model).

**Comment by DWCTOD** [comment]
感谢大佬回复和分析,我想试着按照项目中的介绍去训练一下,发现在数据集处理的时候就出现问题了
![image](https://user-images.githubusercontent.com/41478810/88996318-7e9eba80-d31f-11ea-9ab0-0f452ea5fcaa.png)
把下载好的数据集放在这个路径下然后运行 python3 WFLW_SetPreparation68.py 报错,根据提示应该是路径的问题导致图片没有读取进去

**Comment by github-luffy** [comment]
> 感谢大佬回复和分析,我想试着按照项目中的介绍去训练一下,发现在数据集处理的时候就出现问题了
> ![image](https://user-images.githubusercontent.com/41478810/88996318-7e9eba80-d31f-11ea-9ab0-0f452ea5fcaa.png)
> 把下载好的数据集放在这个路径下然后运行 python3 WFLW_SetPreparation68.py 报错,根据提示应该是路径的问题导致图片没有读取进去

图片是放在/data/WFLW/raw里面嘛 raw里面放的应该是WFLW的图片目录 是这样的嘛?raw目录下存放的目录应该是如下所示：
0--Parade
1--Handshaking
...

**Comment by github-luffy** [comment]
![image](https://user-images.githubusercontent.com/21214262/88997280-ea822280-d321-11ea-9e3a-82dfaf8b7ad5.png)

**Comment by DWCTOD** [comment]
> > 感谢大佬回复和分析,我想试着按照项目中的介绍去训练一下,发现在数据集处理的时候就出现问题了
> > ![image](https://user-images.githubusercontent.com/41478810/88996318-7e9eba80-d31f-11ea-9ab0-0f452ea5fcaa.png)
> > 把下载好的数据集放在这个路径下然后运行 python3 WFLW_SetPreparation68.py 报错,根据提示应该是路径的问题导致图片没有读取进去
> 
> 图片是放在/data/WFLW/raw里面嘛 raw里面放的应该是WFLW的图片目录 是这样的嘛?

O.O,原来是这样子的,哈哈哈,因为我解压之后还有一个大的文件夹包含里面的小文件,现在可以啦哈,太感谢啦

**Comment by DWCTOD** [comment]
不知道大佬对于关键点的抖动,有没有什么好的思路去解决呢? 加跟踪?

**Comment by github-luffy** [comment]
关键点的抖动 是指 测试视频流中的人脸 其特征点抖动的比较厉害？

**Comment by DWCTOD** [comment]
> 关键点的抖动 是指 测试视频流中的人脸 其特征点抖动的比较厉害？

是的呀,就是人基本不怎么动的情况下,人脸特征点还是会一直抖动的比较厉害

**Comment by github-luffy** [comment]
刚上传的模型 你测试也会这样的嘛

**Comment by github-luffy** [comment]
1.要保证人脸框不能抖得太厉害，就是前后人脸框位置变化大，当然真实人脸位置移动正常，可以加人脸跟踪方法，人脸跟踪其实也可简单设置；
2.可能人脸特征点模型泛化能力不强，可增加数据训练。

**Comment by DWCTOD** [comment]
是呀,其实这种抖动,就是人基本正常不怎么动的时候也会存在的

**Comment by YUHANGZHANG7** [comment]
你好 @github-luffy  ，我想问一下我根据已有98点（https://github.com/polarisZhao/PFLD-pytorch）代码训练出来的98点的NME只有0.07左右，我看到你在另外一个工程里说到的调优方法，不知道对应的具体的网络是哪个？

谢谢

**Comment by github-luffy** [comment]
> 你好 @github-luffy ，我想问一下我根据已有98点（[https://github.com/polarisZhao/PFLD-pytorch）代码训练出来的98点的NME只有0.07左右，我看到你在另外一个工程里说到的调优方法，不知道对应的具体的网络是哪个？](https://github.com/polarisZhao/PFLD-pytorch%EF%BC%89%E4%BB%A3%E7%A0%81%E8%AE%AD%E7%BB%83%E5%87%BA%E6%9D%A5%E7%9A%8498%E7%82%B9%E7%9A%84NME%E5%8F%AA%E6%9C%890.07%E5%B7%A6%E5%8F%B3%EF%BC%8C%E6%88%91%E7%9C%8B%E5%88%B0%E4%BD%A0%E5%9C%A8%E5%8F%A6%E5%A4%96%E4%B8%80%E4%B8%AA%E5%B7%A5%E7%A8%8B%E9%87%8C%E8%AF%B4%E5%88%B0%E7%9A%84%E8%B0%83%E4%BC%98%E6%96%B9%E6%B3%95%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E5%AF%B9%E5%BA%94%E7%9A%84%E5%85%B7%E4%BD%93%E7%9A%84%E7%BD%91%E7%BB%9C%E6%98%AF%E5%93%AA%E4%B8%AA%EF%BC%9F)
> 
> 谢谢

mobileNetV3_large或者blazeface,你都可以试试

**Comment by zcxxlshirley** [comment]
请问
运行 camera.py  
抛出terminate called after throwing an instance of 'dmlc::Error'
Aborted (core dumped)
是怎么回事呢？

**Comment by github-luffy** [comment]
> 请问
> 运行 camera.py
> 抛出terminate called after throwing an instance of 'dmlc::Error'
> Aborted (core dumped)
> 是怎么回事呢？

用了mxnet，你可能安装的不是gpu版本，先卸载mxnet，然后安装[mxnet-gpu](https://blog.csdn.net/chenhaifeng2016/article/details/67634763)版本

**Comment by github-luffy** [comment]
EfficientNet系列的模型已更新，速度快，精度高，奥力给！

**Comment by lfxx** [comment]
> EfficientNet系列的模型已更新，速度快，精度高，奥力给！

您好，更新后的预训练模型有吗，想测试一下效果．测试了best_model.pth,感觉效果不是很好.另外想问您一下，输出的关键点置信度有什么意义呢，表示点位置的精准度吗．使用best_model.pth测试时关键点置信度并不是很高

**Comment by github-luffy** [comment]
best_model.pth是利用300W与WFLW两个训练集训练出来的最好模型，使用BlazeLandmark网络，应该还可以继续调优。
输出的关键点置信度是指关键点热力图，正常来说置信度越高，表示是人脸关键点的可能性越高。

**Comment by lfxx** [comment]
> best_model.pth是利用300W与WFLW两个训练集训练出来的最好模型，使用BlazeLandmark网络，应该还可以继续调优。
> 输出的关键点置信度是指关键点热力图，正常来说置信度越高，表示是人脸关键点的可能性越高。

谢谢您的回复，看了下源码，这个置信度其实并不是图像分类中的置信度，其实是位置归一化后的数值，乘上宽高以后就可以得到点位的坐标．这样理解对吗？
另外如果训练时的人脸提取器和推理时的不一样，比如用mtcnn提取人脸位置用于训练,retinaface提取人脸用于推理，会影响检测效果吗？

**Comment by github-luffy** [comment]
训练特征点时需要归一化操作，编码与解码的一个过程。
训练样本不一样，检测效果肯定不一样。

**Comment by 17601614169** [comment]
![image](https://user-images.githubusercontent.com/48199714/91402191-95c7be00-e873-11ea-8d13-d48c28cbbdee.png)
能把这个文件发一下吗？运行camera.py就出现这个错。

**Comment by github-luffy** [comment]
> ![image](https://user-images.githubusercontent.com/48199714/91402191-95c7be00-e873-11ea-8d13-d48c28cbbdee.png)
> 能把这个文件发一下吗？运行camera.py就出现这个错。

安装了mxnet-gpu吗

**Comment by 17601614169** [comment]
感谢回复。给你发了之后我才发现我的电脑是AMD的，现在正在尝试CPU运行。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "叶修强"<notifications@github.com&gt;; 
发送时间: 2020年8月27日(星期四) 下午2:51
收件人: "github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;; 
抄送: "♚丨勿忘心安💢"<799073422@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





  

 能把这个文件发一下吗？运行camera.py就出现这个错。
  
安装了mxnet-gpu吗

**Comment by 17601614169** [comment]
代码使用的是Python哪个版本？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午2:51
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





  

 能把这个文件发一下吗？运行camera.py就出现这个错。
  
安装了mxnet-gpu吗

**Comment by github-luffy** [comment]
python3.6

**Comment by 17601614169** [comment]
好的，谢谢。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午3:24
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





 
python3.6

**Comment by 17601614169** [comment]
博主您好，如果我想用图片测试的话需要运行哪个代码？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午2:51
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





  

 能把这个文件发一下吗？运行camera.py就出现这个错。
  
安装了mxnet-gpu吗

**Comment by github-luffy** [comment]
[test.py](https://github.com/github-luffy/PFLD_68points_Pytorch/blob/master/test.py)

**Comment by github-luffy** [comment]
> 博主您好，如果我想用图片测试的话需要运行哪个代码？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "github-luffy/PFLD_68points_Pytorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月27日(星期四) 下午2:51 收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;; 抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1) 能把这个文件发一下吗？运行camera.py就出现这个错。 安装了mxnet-gpu吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

[test.py](https://github.com/github-luffy/PFLD_68points_Pytorch/blob/master/test.py),代码估计也好懂 就不讲了

**Comment by 17601614169** [comment]
好的，谢谢。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午5:07
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





 
test.py

**Comment by github-luffy** [comment]
> 好的，谢谢。

[test.py](https://github.com/github-luffy/PFLD_68points_Pytorch/blob/master/test.py),代码估计也好懂 就不讲了

**Comment by 17601614169** [comment]
辛苦了。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 下午5:09
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





  
好的，谢谢。
  
test.py,代码估计也好懂 就不讲了

**Comment by github-luffy** [comment]
> 辛苦了。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "github-luffy/PFLD_68points_Pytorch" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月27日(星期四) 下午5:09 收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;; 抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1) 好的，谢谢。 test.py,代码估计也好懂 就不讲了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

不辛苦 点个赞就ok 哈

**Comment by Shzhentao** [comment]
您好，我运行python camera.py 显示No such file or directory: 'test_models2/model_37.pth'，这是什么问题呢？谢谢！

**Comment by 17601614169** [comment]
你去文件路径找找看有这个路径和文件吗？我的里面没有






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 晚上7:41
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





 
您好，我运行python camera.py 显示No such file or directory: 'test_models2/model_37.pth'，这是什么问题呢？谢谢！

**Comment by Shzhentao** [comment]
没有呀

**Comment by 17601614169** [comment]
没有那就换啊，里面有别的模型。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "github-luffy/PFLD_68points_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月27日(星期四) 晚上7:43
收件人:&nbsp;"github-luffy/PFLD_68points_Pytorch"<PFLD_68points_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"♚丨勿忘心安💢"<799073422@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [github-luffy/PFLD_68points_Pytorch] camera.py运行自动闪退了 (#1)





 
没有呀

**Comment by Shzhentao** [comment]
你成功了吗？它显示runtime error: ./pretrained_model/efficientNet-b0.pth is a zip archive，你是加载了哪个

**Comment by 17601614169** [comment]
![image](https://user-images.githubusercontent.com/48199714/91438533-1996a000-e89e-11ea-94b5-96dc1f5b8e89.png)

**Comment by github-luffy** [comment]
> 您好，我运行python camera.py 显示No such file or directory: 'test_models2/model_37.pth'，这是什么问题呢？谢谢！

你可以试试 pretrained_model的几个模型，记得加载模型
![image](https://user-images.githubusercontent.com/21214262/91438635-434fc700-e89e-11ea-9d88-c4a90ef3b981.png)

**Comment by 17601614169** [comment]
我没训练直接跑的test代码，但没成功，根据网上的方法都试过了也不行。
![image](https://user-images.githubusercontent.com/48199714/91438660-4c409880-e89e-11ea-9596-6a5c86acfe84.png)

**Comment by github-luffy** [comment]
> 我没训练直接跑的test代码，但没成功，根据网上的方法都试过了也不行。
> ![image](https://user-images.githubusercontent.com/48199714/91438660-4c409880-e89e-11ea-9596-6a5c86acfe84.png)

人脸检测的retinaface模型是mxnet框架的，你安装的是哪个版本的mxnet，mxnet还是mxnet-gpu？

**Comment by 17601614169** [comment]
> > 我没训练直接跑的test代码，但没成功，根据网上的方法都试过了也不行。
> > ![图片](https://user-images.githubusercontent.com/48199714/91438660-4c409880-e89e-11ea-9596-6a5c86acfe84.png)
> 
> 人脸检测的retinaface模型是mxnet框架的，你安装的是哪个版本的mxnet，mxnet还是mxnet-gpu？

![image](https://user-images.githubusercontent.com/48199714/91439089-03d5aa80-e89f-11ea-81ed-475e2600acbb.png)
cpu

**Comment by 17601614169** [comment]
电脑不是N卡  装gpu也没用吧？

**Comment by Shzhentao** [comment]
您好，请问您用的pytorch版本是多少呀？

**Comment by github-luffy** [comment]
试试安装一下mxnet-gpu,然后跑跑看

**Comment by github-luffy** [comment]
pytorch 1.0以上

**Comment by Shzhentao** [comment]
谢谢您，但是我这里加载模型会显示RuntimeError: ./pretrained_model/blazelandmark.pth is a zip archive(did you mean to use torch.jit.load())
![question](https://user-images.githubusercontent.com/32563958/91439826-3d5ae580-e8a0-11ea-999f-75632430d6fd.JPG)

**Comment by Shzhentao** [comment]
好像说是模型是zip archive架构的

**Comment by github-luffy** [comment]
干脆直接用最新的pytorch版本好了

**Comment by Shzhentao** [comment]
好的，谢谢您，我试试

**Comment by 17601614169** [comment]
![image](https://user-images.githubusercontent.com/48199714/91441182-58c6f000-e8a2-11ea-91cd-21e69ae6f072.png)
换成gpu就出这个错了，头大
