### ISSUE TITLE
代码的数据处理中没看到crop部分

### ISSUE THREAD

**Issue by ganqi91** [github-luffy/PFLD_68points_Pytorch#10]
看到生成训练数据的时候，根据关键点点位信息生成了人脸框信息，但是在dataloader里似乎是直接读取图片地址，未进行crop操作。是因为原始训练数据都是crop之后的嘛？

**Comment by github-luffy** [comment]
对的 在原始训练数据进行了左右翻转 旋转等增强操作 没有考虑crop的操作 你可以试试
