### ISSUE TITLE
模型

### ISSUE THREAD

**Issue by billionfish** [github-luffy/PFLD_68points_Pytorch#11]
请问预训有大模型吗 resnet那种

**Comment by github-luffy** [comment]
没用过resnet大模型 不过尝试了resnest50的模型 效果还不错

**Comment by billionfish** [comment]
试了下预训练的模型

RuntimeError: ./pretrained_model/mobileNetV2_1.0.pth is a zip archive (did you mean to use torch.jit.load()?)

好像模型载入不进去，请问你的torch是什么版本？

**Comment by github-luffy** [comment]
torch 1.5.0 torchvision 0.6.0
