### ISSUE TITLE
关于数据集处理

### ISSUE THREAD

**Issue by Brystone** [github-luffy/PFLD_68points_Pytorch#12]
请问300w数据集是将 afw、helen、ibug、lfpw整个文件夹放在raw目录下吗，准备数据时总是会读不到图片?期待您的回复

**Comment by github-luffy** [comment]
> 请问300w数据集是将 afw、helen、ibug、lfpw整个文件夹放在raw目录下吗，准备数据时总是会读不到图片?期待您的回复

对的 四个目录都放在raw目录下  注意ibug有张图片的名称中间是多了一个空格符号 应该去掉这个空格就没问题啦

**Comment by Brystone** [comment]
> > 请问300w数据集是将 afw、helen、ibug、lfpw整个文件夹放在raw目录下吗，准备数据时总是会读不到图片?期待您的回复
> 对的 四个目录都放在raw目录下 注意ibug有张图片的名称中间是多了一个空格符号 应该去掉这个空格就没问题啦


谢啦，是ibug第92张图片格式有问题。您的代码中ION 是计算的 [72:74] 和[90:92] 也就是73 和 91 这两点的距离，请问这个是按照98点来的吗，如果是 那么计算IPN 应该是 [72:80] 和 [87:95]，但是跑出来不对，请问您是怎么算的呢?

**Comment by github-luffy** [comment]
ION用到的两个点是两眼外眼角间距离（序号为36与45的点），点坐标是由x,y组成，故68*2=136维数组，那么第36的x，y值应该为72，73 同理第45的x,y值应该为90，91 
IPN用到的两个点是两眼瞳孔间距离，这两个点需要自己先求出来,再计算两点的距离
left_centerx = (x36+x37+x38+x39+x40+x41)/6
left_centery = (y36+y37+y38+y39+y40+y41)/6
right_centerx = (x42+x43+x44+x45+x46+x47)/6
right_centery = (y42+y43+y44+y45+y46+y47)/6

**Comment by Brystone** [comment]
> ION用到的两个点是两眼外眼角间距离（序号为36与45的点），点坐标是由x,y组成，故68*2=136维数组，那么第36的x，y值应该为72，73 同理第45的x,y值应该为90，91
> IPN用到的两个点是两眼瞳孔间距离，这两个点需要自己先求出来,再计算两点的距离
> left_centerx = (x36+x37+x38+x39+x40+x41)/6
> left_centery = (y36+y37+y38+y39+y40+y41)/6
> right_centerx = (x42+x43+x44+x45+x46+x47)/6
> right_centery = (y42+y43+y44+y45+y46+y47)/6

谢谢您的回复，代码我理解错了。

**Comment by DanielXu123** [comment]
想问一下300VW raw下面的文件夹目录是怎么放置的呢？？
代码里好像是直接去读~/PFLD_68points_Pytorch/data/300VW/raw/300VW_Dataset_2015_12_14下的vid.avi文件了。但是我把300VW压缩包解压之后还有很多子文件夹，001,002等
