### ISSUE TITLE
"getNewFacialLandmarksFromFacePP.py" is incomplete

### ISSUE THREAD

**Issue by xieshenru** [github-luffy/PFLD_68points_Pytorch#15]
"getNewFacialLandmarksFromFacePP.py" is incomplete,Can you provide the full version?

**Comment by github-luffy** [comment]
Apply for the key and secret of the facial feature point api of face++, and then put them in your_api_key and your_api_secret.

payload = {'api_key':'your_api_key',  'api_secret':'your_api_secret', 'return_landmark':2}

**Comment by xieshenru** [comment]
> Apply for the key and secret of the facial feature point api of face++, and then put them in your_api_key and your_api_secret.
> 
> payload = {'api_key':'your_api_key', 'api_secret':'your_api_secret', 'return_landmark':2}

thank for your reply!
