### ISSUE TITLE
300W的setpreparation部分

### ISSUE THREAD

**Issue by zhou-th** [github-luffy/PFLD_68points_Pytorch#17]
你好！我在运行300wsetpreparation.py时出现了一些错误：

/project/PFLD_N/data/300W/train_data
3283
Traceback (most recent call last):
  File "300W_SetPreparation68.py", line 226, in <module>
    imgs = get_dataset_list(imgDir, outDir, landmarkDir, is_train)  
  File "300W_SetPreparation68.py", line 194, in get_dataset_list
    Img.load_data(is_train, 10, Mirror_file)   
  File "300W_SetPreparation68.py", line 87, in load_data
    height, width, _ = img.shape   
AttributeError: 'NoneType' object has no attribute 'shape'

但是检查后都是按照readme的规定来做的，而且WFLW的set.py可以正确运行，请问是哪里出现了问题吗？

**Comment by github-luffy** [comment]
查看图片路径对不对 错误是因为没读取到图片

**Comment by zhou-th** [comment]
谢谢回复，问题已经解决了！还有想请教一下训练出来的模型对于眨眼敏感吗，对于眼睛部分的关键点检测精度如何？因为还在训，短时间内看不到结果，想来咨询一下

**Comment by github-luffy** [comment]
没试过眨眼的情况，如果想提高眼睛的关键点精度，可考虑针对眼睛部位来增加数据的丰富度（保证数据包含眼睛的多样性，例如眨眼，闭眼等等）；
