### ISSUE TITLE
请问ResNest50模型结果是如何训练得到的呀？

### ISSUE THREAD

**Issue by my-yy** [github-luffy/PFLD_68points_Pytorch#19]
这是个很棒的项目~
我看到给出的结果中，ResNest50的mean error=0.046，failure rate=0.038
我用WFLW数据集跑了100个epoch，最后分数是 mean error=0.086,failure rate=0.241
请问是不是因为训练轮数太短，或者是需要一些其它训练技巧，亦或使用的数据集存在差异？

**Comment by github-luffy** [comment]
不好意思 表格的数据未注明使用的数据 我这边并非只使用了WFLW 还包括其他的数据集 另外的训练条件都一样

**Comment by my-yy** [comment]
十分感谢~
