### ISSUE TITLE
AuxiliaryNet的优化问题

### ISSUE THREAD

**Issue by Qidian213** [github-luffy/PFLD_68points_Pytorch#20]
在train_model.py 中包含AuxiliaryNet的实例化，转 train()模式，但是在优化器，及整个过程中并没有对AuxiliaryNet参数更新的过程。 请教该如何理解AuxiliaryNet在模型训练中的作用？

**Comment by github-luffy** [comment]
AuxiliaryNet参数不更新，这是肯定不对的，已经修正过来了。
AuxiliaryNet主要是预测人脸的三个角度，然后在函数[get_euler_angle_weights](https://github.com/github-luffy/PFLD_68points_Pytorch/blob/master/train_model.py)中用到了计算。
论文从损失函数入手，非常巧妙的解决了平衡各类情况（侧脸、低头、抬头等）训练样本不均衡的问题。

**Comment by Qidian213** [comment]
感谢
