### ISSUE TITLE
不同img_cropped区域得到的关键点效果差距较大

### ISSUE THREAD

**Issue by 7aughing** [github-luffy/PFLD_68points_Pytorch#28]
非常感谢您开源的代码，但是当我使用不同大小的face crop时，得到的关键点效果差距比较大，可以请教下这是为什么吗？(下图紫色框是表示不同的face crop)
![image](https://user-images.githubusercontent.com/30593398/112999027-27e4cb80-91a1-11eb-9469-fa8ec5211f79.png)
![image](https://user-images.githubusercontent.com/30593398/112999045-2ca97f80-91a1-11eb-9985-8c7ad095dd95.png)

**Comment by github-luffy** [comment]
训练的时候 数据集是用的哪种face_crop?

**Comment by duantiantian** [comment]
第一种，跟您的代码一致，没有改动您的代码。但是我不太理解的是，当使用不同的人脸检测器，得到的face crop不同时，关键点的结果会不同。我以为只要输入的face crop可以包含完整的人脸，关键点的位置就应该是一致的。

**Comment by 7aughing** [comment]
> 训练的时候 数据集是用的哪种face_crop?

第一种，跟您的代码一致，没有改动您的代码。但是我不太理解的是，当使用不同的人脸检测器，得到的face crop不同时，关键点的结果会不同。我以为只要输入的face crop可以包含完整的人脸，关键点的位置就应该是一致的。

**Comment by github-luffy** [comment]
喔喔 输入的图片是多大分辨率的 112*112？

**Comment by duantiantian** [comment]
> 喔喔 输入的图片是多大分辨率的 112*112？

输入的图片大小不等，但是经过人脸检测器得到face crop之后，会根据您的代码resize到112*112。这是我输入的一张1104 × 1472的图片，使用retinaface作为face detector，得到的结果好像不是很准(只画了四个点)。
![image](https://user-images.githubusercontent.com/30593398/113115421-00dcd700-923f-11eb-9349-197a57ff521a.png)

**Comment by github-luffy** [comment]
喔喔 将第一种与第二种face_crop后分别resize为112*112，对比看看人脸。应该是第二种人脸变形更严重吧？

**Comment by 7aughing** [comment]
是的是的，所以是不是可以尝试将图片长边resize到112，短边使用相同的ratio进行resize，然后填充到112？

**Comment by github-luffy** [comment]
正常来说 训练与测试 图片预处理方式应该是要保持一致的 这样的准确率才能更好 不过你可以尝试一下 也许有用

**Comment by 7aughing** [comment]
对，讲道理应该要保持一致。所以针对输入图片分辨率过大，导致测试结果不太准，您有什么建议吗？比如在训练集中增加该尺度的图片？

**Comment by github-luffy** [comment]
这也是一种办法 丰富训练集的多样性

**Comment by fire717** [comment]
看效果我感觉不是模型精度的问题 点明显都预测对了 只是位置有一个偏移
要是模型的精度问题一般不会是这种现象
要么是你输出点换算到原图绝对坐标有问题 要么是画点的时候转换的问题  建议好好检查
