### ISSUE TITLE
关于PFLD网络的精度

### ISSUE THREAD

**Issue by hot-dog** [github-luffy/PFLD_68points_Pytorch#3]
大佬，有个问题请教下，PFLD这个算法的精度怎么样，大佬你实现的这个版本精度有达到论文里说的水平不，纯新手小白一枚，想找个近两年最新最好的网络学习一下。

**Comment by github-luffy** [comment]
此版本是基于68点特征点（项目用68点就够了），与论文中的实验不同，关键是速度与精度折中，追求项目的落地。
与论文较匹配的情况，其训练过程中最好的效果：mean error:0.055，failure rate:0.086，单独用WFLW的98点特征点训练出来的，具体情况可参照[提升精度问题](https://github.com/guoqiangqi/PFLD/issues/28)，若需验证论文的实验结果，可试试[PFLD](https://github.com/guoqiangqi/PFLD)。
最新的网络建议去学习一下efficientNet，已用于图像分类，目标检测（EfficientDet），图像分割（EfficientPS）等领域，也有相应的论文与代码。

**Comment by hot-dog** [comment]
感谢回复，还有些疑问想请教下，就人脸关键点检测这个任务，当前的sota网络是哪个？还有人脸关键点检测这个任务是不是已经比较成熟了，最近两年的CVPR，ECCV等的论文似乎很少看到跟人脸关键点检测相关的论文。另外不知道是不是因为涉及到商业的原因，github上有关人脸关键点检测的开源工程很少，有啥相关的开源项目可以推荐一下不。再次感谢！

**Comment by github-luffy** [comment]
> 感谢回复，还有些疑问想请教下，就人脸关键点检测这个任务，当前的sota网络是哪个？还有人脸关键点检测这个任务是不是已经比较成熟了，最近两年的CVPR，ECCV等的论文似乎很少看到跟人脸关键点检测相关的论文。另外不知道是不是因为涉及到商业的原因，github上有关人脸关键点检测的开源工程很少，有啥相关的开源项目可以推荐一下不。再次感谢！

效果较好的开源项目：
 [tensorflow PFLD](https://github.com/guoqiangqi/PFLD)
 [Pytorch PFLD](https://github.com/polarisZhao/PFLD-pytorch)
 [Caffe LAB](https://github.com/wywu/LAB)
其实关键在于商业落地，而工业落地又在于高质量 多样化 适用性强的数据，具体场景具体分析，算法基于数据驱动。
一般来说数据越多越丰富，效果越好，标注的特征点越多，效果越稳定（特征点不易抖动）。
[1000点和106点的差别](https://www.chinaz.com/news/mt/2018/1229/977036.shtml)

**Comment by hot-dog** [comment]
了解了，非常感谢！！
