### ISSUE TITLE
train_model.py中的一点疑问

### ISSUE THREAD

**Issue by 7aughing** [github-luffy/PFLD_68points_Pytorch#37]
hi，我在改代码的时候发现，你的train_model.py 里 line158 是这样的：
```py
pre_landmarks, auxiliary_features = model(images_batch)
```

而 line201 里是这样的：
```py
pre_landmarks, euler_angles_pre = model(images_batch)
```

line201 是写错了吗？

**Comment by github-luffy** [comment]
> hi，我在改代码的时候发现，你的train_model.py 里 line158 是这样的：
> 
> ```python
> pre_landmarks, auxiliary_features = model(images_batch)
> ```
> 
> 而 line201 里是这样的：
> 
> ```python
> pre_landmarks, euler_angles_pre = model(images_batch)
> ```
> 
> line201 是写错了吗？


训练阶段用到了辅助网络 测试阶段没有用到 应该是一样的名字 或者一样的输出结果 忘了改！！！

**Comment by 7aughing** [comment]
好滴
