### ISSUE TITLE
人脸质量筛选

### ISSUE THREAD

**Issue by thenighthunter0** [github-luffy/PFLD_68points_Pytorch#4]
没有人脸，和人脸偏的很厉害的情形，反而会预测出类似正脸的结果，PFLD没有处理策略。这样会影响人脸质量筛选，无法筛选出轨迹中的好脸，大佬有没有研究过这个问题，有没有什么解决策略？

**Comment by github-luffy** [comment]
没有人脸，正常来说是不做预测的，而人脸非常偏的情况可以试试添加类似的训练数据，尽量提升此情况的精度。

**Comment by thenighthunter0** [comment]
试试
