### ISSUE TITLE
训练多少个epoch后loss能正常收敛

### ISSUE THREAD

**Issue by leizhu1989** [github-luffy/PFLD_68points_Pytorch#40]
你好作者！
我训练efficientnet-b0，第三十个epoch了loss还非常大，这正常吗？
Epoch:[34  ][26  /26  ]	Loss: 29673.287	 lr 1e-05	 average_time:3.871s	 remain_time:13.001h
Test epochs: 5	Loss 46748736.800
mean error and failure rate
mean error : 1.672
failure rate: L1 0.866

**Comment by leizhu1989** [comment]
使用的是300W数据集

**Comment by github-luffy** [comment]
> 你好作者！ 我训练efficientnet-b0，第三十个epoch了loss还非常大，这正常吗？ Epoch:[34 ][26 /26 ]	Loss: 29673.287	lr 1e-05	average_time:3.871s	remain_time:13.001h Test epochs: 5	Loss 46748736.800 mean error and failure rate mean error : 1.672 failure rate: L1 0.866


初始学习率 batchsize分别设置为多少

**Comment by leizhu1989** [comment]
学习率是0.0001，batchsize是128，都是默认值，单卡训练的

**Comment by github-luffy** [comment]
> 学习率是0.0001，batchsize是128，都是默认值，单卡训练的

从头再跑下看看，多试几次

**Comment by leizhu1989** [comment]
我跑完了resnet的500个epoch，loss是3000多，128batchsize，test的loss依然是170万多，这是没收敛吧，为啥会这样呢，跑几次了

**Comment by github-luffy** [comment]
> 我跑完了resnet的500个epoch，loss是3000多，128batchsize，test的loss依然是170万多，这是没收敛吧，为啥会这样呢，跑几次了

训练loss和测试loss应该是不正常的 检查下标签 最好可视化看看输入的原图和标签有没有问题 把特征点输出在图片上看看。

**Comment by leizhu1989** [comment]
我看到了代码里面有对图片进行resize，没看到对landmarks_gt做resize，不知道是不是这个原因
    train_data_transforms = tv.transforms.Compose([
        tv.transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.2),
        tv.transforms.Resize((args.image_size, args.image_size)),
        tv.transforms.ToTensor()
    ])

**Comment by leizhu1989** [comment]
你好作者貌似找到原因了，我忘了crop图的那个脚本
