### ISSUE TITLE
关于coco里的关键点

### ISSUE THREAD

**Issue by PureHing** [github-luffy/PFLD_68points_Pytorch#48]
@github-luffy 
你好 请问一下为何PFLD都没有用coco里的68个face关键点呢？

**Comment by github-luffy** [comment]
有68点当然可以用，我这边暂时没有用上这个数据集。

**Comment by PureHing** [comment]
@github-luffy 嗯。
我看到你在[这里](https://github.com/guoqiangqi/PFLD/issues/47#issuecomment-668925121)之前有评论过，想请教一下，远距离的场景不知道你是否测试过是否有偏移呢？

**Comment by github-luffy** [comment]
偏移过，不过只是偶尔。
