### ISSUE TITLE
BlazeLandMark预训练模型

### ISSUE THREAD

**Issue by duduheihei** [github-luffy/PFLD_68points_Pytorch#5]
感谢luffy的分享，想测试下BlazeLandMark模型的效果，请问能提供一下预训练模型吗

**Comment by github-luffy** [comment]
> 感谢luffy的分享，想测试下BlazeLandMark模型的效果，请问能提供一下预训练模型吗

[best_model.pth](https://github.com/github-luffy/PFLD_68points_Pytorch/tree/master/pretrained_model)

**Comment by duduheihei** [comment]
感谢，另外请问RetinaFace和MTCNN的人脸检测，哪个和提供的landmark模型更加匹配？

**Comment by github-luffy** [comment]
同等数据下，RetinaFace效果一般会优于MTCNN，建议使用RetinaFace。

**Comment by duduheihei** [comment]
OK 多谢，另外建议把blazeFace、mobileNetV2、EfficientNet三者的速度和精度对比罗列一下，方便大家选用
