### ISSUE TITLE
代码loss中没有考虑类不平衡问题的属性权重？

### ISSUE THREAD

**Issue by YjDai** [github-luffy/PFLD_68points_Pytorch#8]
你好， 代码loss中没有考虑类不平衡问题的属性权重？

**Comment by github-luffy** [comment]
考虑到自身添加数据后 需要人为判别其类别属性 成本高且不好判断（人为误差）去除了类别属性权重

**Comment by YjDai** [comment]
好的，谢谢

**Comment by github-luffy** [comment]
> 好的，谢谢

客气 留赞ok？ 哈

**Comment by YjDai** [comment]
请问mobilenet-v2-0.25实测的效果好吗，我这边训练的飘的比较厉害，很不稳定

**Comment by github-luffy** [comment]
> 请问mobilenet-v2-0.25实测的效果好吗，我这边训练的飘的比较厉害，很不稳定

可以将飘的比较厉害的图片打印出来 然后查看一下 确认是角度很大的人脸还是正常人脸？

**Comment by YjDai** [comment]
我是在线测试的，正对着测试也飘的比较厉害

**Comment by github-luffy** [comment]
> 我是在线测试的，正对着测试也飘的比较厉害

喔喔 可能输出特征点的网络较浅 而辅助网络（输出三个角度）的模型较强 极有可能都学到角度大的人脸去了 裁剪一下辅助网络或者干脆不要 再训练一下 试试看
